# Project EdgeAI

## Import library to get data

In [1]:
import requests, os, shutil

listQuery = ["Emberiza citrinella", "Alauda arvensis", "Emberiza cirlus", "Cuculus canorus"] #, "Tyto alba", "Falco tinnunculus", "Sylvia borin", "Muscicapa striata", "Tachybaptus ruficollis", "Delichon urbicum"]

## Import data from API

In [ ]:
url = "https://xeno-canto.org/api/2/recordings?query="

def enregistrer_mp3(url_api, nom_fichier):
    reponse = requests.get(url_api, stream=True)
    
    if reponse.status_code == 200:
        with open(nom_fichier, 'wb') as fichier_audio:
            reponse.raw.decode_content = True
            shutil.copyfileobj(reponse.raw, fichier_audio)
        print("Audio enregistré avec succès sous le nom :", nom_fichier)
    else:
        print("Erreur lors de la récupération des données audio depuis l'API")

def getData(query):
    url_api = url + query
    response = requests.get(url_api)

    if response.status_code == 200:
        contenu = response.json()["recordings"]
        pathToDir = "./data/" + query

        if not os.path.exists(pathToDir):
            os.mkdir(pathToDir)

            for _, element in zip(range(250), contenu):
                elementUrl = element["file"]
                elementFileName = element["file-name"]
                storeFile = pathToDir + "/" + elementFileName
                
                if not os.path.exists(storeFile):
                    try:
                        enregistrer_mp3(elementUrl, storeFile)
                    except: # Pour les problèmes de noms de fichiers
                        pass

for query in listQuery:
    getData(query)

## Import library to train model

In [2]:
from sklearn import model_selection
from pathlib import Path
import librosa
import copy
import matplotlib
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Input, Conv1D, MaxPool1D, Flatten, Dense, AvgPool1D, Activation
from keras.utils import get_file
from keras.utils import to_categorical

dataset_dir = Path('data')

## Load all sound in X and Y

In [3]:
x = []
y = []

def slice_audio_with_trim(file_path, index, duration=1):
    audio_data, sampling_rate = librosa.load(file_path, sr=None)
    non_silent_audio, _ = librosa.effects.trim(audio_data)
    num_slices = int(len(non_silent_audio) / sampling_rate / duration)

    # Diviser l'audio en fonction de duration
    for i in range(num_slices):
        start = i * sampling_rate * duration
        end = start + sampling_rate * duration
        slice_data = non_silent_audio[start:end]

        data = slice_data.astype(np.float32)
        data.resize((16000, 1))

        x.append(data)
        y.append(index)

def getAllDataClasses(directory, index):
    for recording in dataset_dir.glob(f'{directory}/*'):
        slice_audio_with_trim(str(recording) ,index)

def loadAllData():
    for i in range(len(listQuery)):
        getAllDataClasses(listQuery[i], i)

loadAllData()

In [4]:
u, indexes, counts = np.unique(y, return_index=True, return_counts=True)
min = np.min(counts)
nbrClasses = len(u)

indices = np.random.permutation(min)

newX = []
newY = []

for i in range(nbrClasses):
    sousSetX = []
    sousSetY = []
    
    if i == nbrClasses - 1:
        sousSetX = x[indexes[i]:]
        sousSetY = y[indexes[i]:]
    else:
        sousSetX = x[indexes[i] : indexes[i + 1]]
        sousSetY = y[indexes[i] : indexes[i + 1]]
    
    x_selectionne = [sousSetX[j] for j in indices]
    y_selectionne = [sousSetY[j] for j in indices]

    for x_s, y_s in zip(x_selectionne, y_selectionne):
        newX.append(x_s)
        newY.append(y_s)

u, indexes, counts = np.unique(newY, return_index=True, return_counts=True)
print(u)
print(indexes)
print(counts)

[0 1 2 3]
[   0 1121 2242 3363]
[1121 1121 1121 1121]


In [5]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(newX, newY, test_size=0.2)
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = to_categorical(np.array(y_train))
y_test = to_categorical(np.array(y_test))


In [6]:
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(3587, 16000, 1) (897, 16000, 1)
(3587, 4) (897, 4)


In [7]:
model = Sequential()
model.add(Input(shape=(16000, 1)))
model.add(Conv1D(filters=4, kernel_size=3, activation='relu'))
model.add(MaxPool1D(pool_size=8))
model.add(Conv1D(filters=4, kernel_size=3, activation='relu'))
model.add(MaxPool1D(pool_size=2))
model.add(Flatten())
model.add(Dense(units=4))
model.add(Activation('softmax')) # SoftMax activation needs to be separate from Dense to remove it later on
# EXPLORE Learning Rate
opt = tf.keras.optimizers.Adam(learning_rate=10e-4)
model.summary()
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['categorical_accuracy'])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 15998, 4)          16        
                                                                 
 max_pooling1d (MaxPooling1D  (None, 1999, 4)          0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 1997, 4)           52        
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 998, 4)           0         
 1D)                                                             
                                                                 
 flatten (Flatten)           (None, 3992)              0         
                                                                 
 dense (Dense)               (None, 4)                 1

In [8]:
model.fit(x_train, y_train, epochs=50, batch_size=384, validation_data=(x_test, y_test))
# model.fit(x_train, y_train, epochs=25, batch_size=268, validation_data=(x_test, y_test))

Epoch 1/50
10/10 [==============================] - 3s 275ms/step - loss: 1.3858 - categorical_accuracy: 0.2715 - val_loss: 1.3834 - val_categorical_accuracy: 0.3512
Epoch 2/50
10/10 [==============================] - 3s 257ms/step - loss: 1.3709 - categorical_accuracy: 0.3490 - val_loss: 1.3441 - val_categorical_accuracy: 0.2598
Epoch 3/50
10/10 [==============================] - 2s 250ms/step - loss: 1.3088 - categorical_accuracy: 0.2715 - val_loss: 1.2445 - val_categorical_accuracy: 0.3790
Epoch 4/50
10/10 [==============================] - 2s 239ms/step - loss: 1.2141 - categorical_accuracy: 0.3546 - val_loss: 1.1680 - val_categorical_accuracy: 0.4615
Epoch 5/50
10/10 [==============================] - 2s 238ms/step - loss: 1.1572 - categorical_accuracy: 0.4904 - val_loss: 1.1366 - val_categorical_accuracy: 0.4783
Epoch 6/50
10/10 [==============================] - 2s 247ms/step - loss: 1.1367 - categorical_accuracy: 0.4976 - val_loss: 1.1265 - val_categorical_accuracy: 0.4950
Epoc

In [9]:
model.evaluate(x_test, y_test, verbose=2)
pred_test = model.predict(x_test)
print(tf.math.confusion_matrix(y_test.argmax(axis=1), pred_test.argmax(axis=1)))

29/29 - 0s - loss: 0.7419 - categorical_accuracy: 0.6667 - 283ms/epoch - 10ms/step
29/29 [==============================] - 0s 9ms/step
tf.Tensor(
[[175  19  20   9]
 [ 22 177   5   0]
 [157  32  38  14]
 [ 17   0   4 208]], shape=(4, 4), dtype=int32)


In [10]:
model.save('project.h5')

In [11]:
%pip install qualia_codegen_core
import qualia_codegen_core
from qualia_codegen_core.graph.KerasModelGraph import KerasModelGraph
from qualia_codegen_core.graph.Quantization import Quantization
from qualia_codegen_core.graph.RoundMode import RoundMode

from importlib.resources import files
main_path = str((files('qualia_codegen_core.examples')/'Linux'/'main.cpp').resolve())

Cannot find PyTorch, PyTorch framework will be unavailable


Note: you may need to restart the kernel to use updated packages.


In [12]:
modelgraph = KerasModelGraph(model).convert()
print(modelgraph)

—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
Inputs                                           | Layer                                            | Outputs                                          | Input shape                                      | Output shape                                    
—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
                                                 | input_1                                          | conv1d                                           | (1, 16000, 1)                                    | ((1, 16000, 1),)                   

In [16]:
float_modelgraph = copy.deepcopy(modelgraph)

# layer quantization annotations for float32
for node in float_modelgraph.nodes:
    # No scale factor if not fixed-point quantization on integers
    node.q = Quantization(
            number_type=float,
            width=32,
            long_width=32,
            weights_scale_factor=0,
            output_scale_factor=0,
            weights_round_mode=RoundMode.NONE,
            output_round_mode=RoundMode.NONE,
            )

float_res = qualia_codegen_core.Converter(output_path=Path('gsc_output_floating')).convert_model(float_modelgraph)

with open('gsc_model_floating.h', 'w') as f:
    f.write(float_res)

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\activation
......vars
...layers\conv1d
......vars
.........0
.........1
...layers\conv1d_1
......vars
.........0
.........1
...layers\dense
......vars
.........0
.........1
...layers\flatten
......vars
...layers\max_pooling1d
......vars
...layers\max_pooling1d_1
......vars
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2024-04-21 23:51:27         3128
metadata.json                                  2024-04-21 23:51:27           64
variables.h5                                   2024-04-21 23:51:27       223432
Keras model

Graphviz not available
Activation function TActivation.SOFTMAX not supported
ModelGraph validation failed


Keras weights file (<HDF5 file "variables.h5" (mode r)>) loading:
...layers\activation
......vars
...layers\conv1d
......vars
.........0
.........1
...layers\conv1d_1
......vars
.........0
.........1
...layers\dense
......vars
.........0
.........1
...layers\flatten
......vars
...layers\max_pooling1d
......vars
...layers\max_pooling1d_1
......vars
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
None


TypeError: write() argument must be str, not None

In [14]:
!g++ -std=c++17 -Wall -Wextra -pedantic -Ofast -o gsc_fixed -include gsc_output_fixed/include/defines.h -Igsc_output_fixed/include gsc_output_fixed/model.c {main_path}

cc1plus.exe: fatal error: gsc_output_fixed/model.c: No such file or directory
compilation terminated.
<command-line>: fatal error: gsc_output_fixed/include/defines.h: No such file or directory
compilation terminated.
